"""
Apply threat level upgrades to real outbreaks in threat-data.ts.

Rules:
  - Real outbreak + особо опасная + карантин → critical
  - Real outbreak + особо опасная (без карантина) → high (min)
  - Real outbreak + другая болезнь → high (min)

We only MODIFY lines where level needs to change.
We do NOT touch non-real threats.
"""

import re
from pathlib import Path

DATA_FILE = Path('/home/z/my-project/src/lib/threat-data.ts')

# Changes: (id, new_level)
# Generated by review_real_levels.py
CHANGES = {
    '2':  'critical',  # АЧС Ростовская — карантин
    '4':  'critical',  # Птичий грипп Ростовская — карантин
    '6':  'critical',  # Птичий грипп Краснодарский — карантин
    '8':  'high',      # Бруцеллёз Краснодарский — real, был medium
    '10': 'critical',  # Бешенство Адыгея — карантин
    '11': 'critical',  # Бешенство Крым — карантин
    '12': 'critical',  # АЧС Крым — карантин
    '13': 'high',      # Нодулярный дерматит Крым — real, был medium
    '14': 'high',      # Бруцеллёз Крым — real, был medium
    '15': 'critical',  # Бешенство Севастополь — карантин
    '16': 'critical',  # Птичий грипп Севастополь — карантин
    '17': 'high',      # Сибирская язва Ростовская — real, был medium
    '18': 'high',      # Сибирская язва Краснодарский — real, был medium
    '20': 'high',      # Болезнь Ньюкасла Ростовская — real, был medium
    '21': 'high',      # Эмкар Ростовская — real, был medium
    '22': 'high',      # Блютанг Ростовская — real, был medium
}

# Read original
content = DATA_FILE.read_text(encoding='utf-8')
original = content

# For each threat id, find its block and replace `threatLevel: 'old'` with `threatLevel: 'new'`
# We need to find the block boundary by scanning for `id: '<id>'` then close on `},\n`

# Regex: match block from `{ id: 'ID'` to `},\n` (next threat)
# We use non-greedy match with re.DOTALL
changed = 0
for tid, new_level in CHANGES.items():
    # Find the block
    # Pattern: { id: 'TID' ... } (closing brace + optional comma + newline)
    block_pattern = re.compile(
        rf"(\{{\s*id:\s*'{re.escape(tid)}'[^}}]*?threatLevel:\s*')(\w+)(')",
        re.DOTALL
    )
    match = block_pattern.search(content)
    if not match:
        print(f'  WARNING: ID {tid} not found')
        continue
    old_level = match.group(2)
    if old_level == new_level:
        print(f'  ID {tid}: already {new_level}, skip')
        continue
    # Replace
    new_str = match.group(1) + new_level + match.group(3)
    content = content[:match.start()] + new_str + content[match.end():]
    print(f'  ID {tid}: {old_level} → {new_level}')
    changed += 1

print(f'\nTotal changes: {changed}')

# Write back
if changed > 0:
    DATA_FILE.write_text(content, encoding='utf-8')
    print(f'Written to {DATA_FILE}')
else:
    print('No changes to write')
